namespace NinjaKiwi.LiNK.DataModels;

[Flags]
public enum GuildMembershipState
{
	NONE = 0,
	JOIN_REJECTED = 1,
	JOIN_BLOCKED = 2,
	JOIN_PENDING = 4,
	IS_MEMBER = 8,
	CAN_ACCEPT_PENDING_MEMBERS = 16,
	CAN_REMOVE_MEMBERS = 32,
	STATE_IS_LOCKED = 64,
	CAN_REVOKE_MEMBER_PERMISSIONS = 128,
	CAN_GRANT_MEMBER_PERMISSIONS = 256,
	CAN_MODIFY_GUILD_INFO = 512,
	CUSTOM_PERMISSION_A = 65536,
	CUSTOM_PERMISSION_B = 131072,
	CUSTOM_PERMISSION_C = 262144,
	MAXIMUM = 2147483647,
}

