namespace Assets.Scripts.Unity.Bridge;

public enum ActionType
{
	Unknown = 0,
	SetCursorAction = 1,
	ContinueFromCheckpointAction = 2,
	ActivateInstaTowerAction = 3,
	ActivatePowerAction = 4,
	ApplyAbilityCustomInputDataAction = 5,
	ApplyTowerBehaviorCustomInputDataAction = 6,
	ApplyTargetTypeDataV2Action = 7,
	ApplyTargetTypeDataV2ArrayAction = 8,
	CollectFromBankAction = 9,
	ContinueAction = 10,
	CoopAction = 11,
	CreateTowerAtAction = 12,
	CursorDownAction = 13,
	CursorUpAction = 14,
	SetFastForwardAction = 15,
	EnterFreeplayAction = 16,
	InteractableClickedAction = 17,
	LoseAction = 18,
	OnInteractWithGizmoAction = 19,
	PerformCustomUIActionAction = 20,
	ActivateAbilityAction = 21,
	PurchaseGeraldoItemAction = 22,
	PurchaseHeroLevelUpAction = 23,
	PurchaseMaxHeroLevelAction = 24,
	RemovePeerAction = 25,
	RequestCashAction = 26,
	RestartAction = 27,
	SellRemovableAction = 28,
	SellTowerAction = 29,
	SendCashAction = 30,
	SendEmoteAction = 31,
	SetAutoplayAction = 32,
	SetNextTowerTargetTypeAction = 33,
	StartRoundAction = 34,
	SendRaceRoundAction = 35,
	PerformTsmThemeActionAction = 36,
	UpgradeHeroToLevelAction = 37,
	UpgradeTowerAction = 38,
	AddGameCompletionTimePenaltyAction = 39,
	WinAction = 40,
	ResumeFromCheckpointAction = 41,
	SetAbilityCustomInputDataAction = 42,
	SellRegenRemovableAction = 43,
	ActivateCorvusSpellAction = 44,
	ClearTargetTypeDataAction = 45,
	ReplayMarkerAction = 46,
}

