namespace NinjaKiwi.GUTS.Models.CT.BTD6;

public enum ContestedTerritoryRelicType
{
	None = -1,
	StartingStash = 0,
	ExtraEmpowered = 1,
	BoxOfChocolates = 2,
	BoxOfMonkey = 3,
	MarchingBoots = 4,
	HeroBoost = 5,
	BiggerBloonSabotage = 6,
	RoundingUp = 7,
	ManaBulwark = 8,
	Regeneration = 9,
	Restoration = 10,
	DurableShots = 11,
	AlchemistTouch = 12,
	DeepHeat = 13,
	Sharpsplosion = 14,
	RoyalTreatment = 15,
	HardBaked = 16,
	Fortifried = 17,
	MoabClash = 18,
	CamoFlogged = 19,
	BrokenHeart = 20,
	GoingTheDistance = 21,
	Heartless = 22,
	FlintTips = 23,
	Abilitized = 24,
	AirAndSea = 25,
	ElDorado = 26,
	MonkeyShield = 27,
	MonkeyShieldMark2 = 28,
	MonkeyShieldMark3 = 29,
	PsiVision = 30,
	OpenSeason = 31,
	CamoTrap = 32,
	Thrive = 33,
	SuperMonkeyStorm = 34,
	MonkeyBoost = 35,
	RoadSpikes = 36,
	MoabMine = 37,
	GlueTrap = 38,
	Techbot = 39,
	PrimaryPrimates = 40,
	MilitaryMonkeys = 41,
	MagicMonkeys = 42,
	SupportSimians = 43,
	MonkeyTycoon = 44,
}

