namespace Assets.Scripts.Models.ServerEvents;

public enum ChallengeModifiers
{
	CeramicHPIncreased = 0,
	FasterBloons = 1,
	NoKnowledge = 2,
	NoLivesLost = 3,
	SlowerBloons = 4,
	CeramicHPDecreased = 5,
	MoabHPIncreased = 6,
	MoabHPDecreased = 7,
	SellingDisabled = 8,
	PowersDisabled = 9,
	NoContinues = 10,
	FasterMoabs = 11,
	SlowerMoabs = 12,
	AllCamo = 13,
	AllRegen = 14,
	NoInstaReward = 15,
	FasterRegen = 16,
	SlowerRegen = 17,
	CustomRounds = 18,
	DisableDoubleCash = 19,
	AbilityCooldownDecreased = 20,
	AbilityCooldownIncreased = 21,
	RemoveableCostDecreased = 22,
	RemoveableCostIncreased = 23,
	LeastCash = 24,
	LeastTiers = 25,
	EndRound = 26,
	StartLives = 27,
	MaxLives = 28,
	Cash = 29,
	BossHPIncreased = 30,
	BossHPDecreased = 31,
	BossSpeedIncreased = 32,
	BossSpeedDecreased = 33,
	ParagonLimit = 34,
	DisableFastTrack = 35,
}

